TIMESTAMP >>> 2022-01-19 23:00:35.621414
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:00:35.904761
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:00:37.150947
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:25.031539
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Menu_data' doesn't exist [SQL: 'SELECT `Menu_data`.link AS `Menu_data_link`, `Menu_data`.name AS `Menu_data_name` \nFROM `Menu_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:25.039155
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Site_data' doesn't exist [SQL: 'SELECT `Site_data`.site_title AS `Site_data_site_title`, `Site_data`.site_logo AS `Site_data_site_logo`, `Site_data`.fav_icon AS `Site_data_fav_icon` \nFROM `Site_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:30.760570
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Menu_data' doesn't exist [SQL: 'SELECT `Menu_data`.link AS `Menu_data_link`, `Menu_data`.name AS `Menu_data_name` \nFROM `Menu_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:30.771222
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Site_data' doesn't exist [SQL: 'SELECT `Site_data`.site_title AS `Site_data_site_title`, `Site_data`.site_logo AS `Site_data_site_logo`, `Site_data`.fav_icon AS `Site_data_fav_icon` \nFROM `Site_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:06:27.619115
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.631320
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.793510
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.800008
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:07:58.382623
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:07:59.489308
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:09:24.549688
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:09:25.711014
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:10:41.272212
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:10:42.171145
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:18.161504
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:18.807706
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:19.261811
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:13:09.987034
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:13:10.152510
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:22.430885
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:25.491362
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:41.929251
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:42.704644
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:21:52.523482
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:22:01.141201
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:20.360597
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:21.461216
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:22.834521
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:49.746459
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-20 00:53:56.727073
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:01.405486
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:35.839622
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:55.084052
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:59.776532
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:55:11.699786
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:56:25.378439
'Announcement' object is not iterable

TIMESTAMP >>> 2022-01-20 00:56:30.256051
'Announcement' object is not iterable

TIMESTAMP >>> 2022-01-20 01:12:20.800543
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 12, 20, 796172)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:26:08.141849
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 26, 8, 138854)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:26:29.885586
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 26, 29, 882700)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:36:16.112501
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 36, 16, 110474)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:42:29.606256
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': 'testing event message', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 42, 29, 603264)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:42:29.607261
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': 'testing event message', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 42, 29, 603264)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-20 03:01:20.341090
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:01:29.044253
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:01:37.656507
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:04:08.459261
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:04:56.495786
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:06:52.391441
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:07:48.099609
'<' not supported between instances of 'NoneType' and 'datetime.datetime'

TIMESTAMP >>> 2022-01-21 00:26:35.238279
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'cccs.announcements' doesn't exist
[SQL: SELECT `Announcements`.event_time AS `Announcements_event_time`, `Announcements`.create_time AS `Announcements_create_time`, `Announcements`.id AS `Announcements_id`, `Announcements`.message AS `Announcements_message` 
FROM `Announcements`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-21 00:26:43.243916
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'cccs.announcements' doesn't exist
[SQL: SELECT `Announcements`.event_time AS `Announcements_event_time`, `Announcements`.create_time AS `Announcements_create_time`, `Announcements`.id AS `Announcements_id`, `Announcements`.message AS `Announcements_message` 
FROM `Announcements`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-21 01:41:46.409871
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:42:28.389158
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:43:05.917478
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:58:23.725551
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:00:02.126189
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:00:23.899517
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:01.164908
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:03.869136
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:29.284997
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:31.185965
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:04:17.146546
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:04:17.151532
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:05:07.014249
list index out of range

TIMESTAMP >>> 2022-01-21 02:10:26.477882
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:11:37.176924
'BaseQuery' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:12:11.797976
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:15:35.225202
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:18:24.761639
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:18:58.611545
'Registrations' object has no attribute 'fname'

TIMESTAMP >>> 2022-01-21 02:19:20.771639
'Registrations' object has no attribute 'fname'

TIMESTAMP >>> 2022-01-21 02:31:33.467858
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': '63ad48f6b92910198697eaf362958a75aca2fa4db2663b11d181de0c991a8e2e', 'salt': 'ouC5qExFaePI0cTl', 'code': 'vRhsaDFVjWBMlXiz', 'expiration': datetime.datetime(2022, 1, 21, 2, 46, 33, 462179)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-21 02:32:54.063488
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': 'eb16b895b32dc6bc2368d66392e4a168a73fe87d58c03a4d153f7cfddef60377', 'salt': 'dF3PHKEWlhnL01s6', 'code': 'WeflJg3ktNmqc6yo', 'expiration': datetime.datetime(2022, 1, 21, 2, 47, 54, 55506)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-21 02:36:43.939521
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:36:43.942514
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:41:54.039724
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:41:54.042716
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:43:12.384957
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:43:12.386952
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:43:57.651875
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:43:57.653748
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:44:24.430720
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:44:24.433712
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:45:02.990365
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:45:02.994354
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:46:12.689677
'BaseQuery' object has no attribute 'flter_by'

TIMESTAMP >>> 2022-01-21 02:46:12.691705
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:47:07.117418
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:49:36.737063
Python type module cannot be converted

