TIMESTAMP >>> 2022-01-19 23:00:35.621414
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:00:35.904761
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:00:37.150947
(mysql.connector.errors.ProgrammingError) 1044 (42000): Access denied for user 'mefisher2'@'%' to database 'mefisher2$cccs' [SQL: "CREATE DATABASE mefisher2$cccs CHARACTER SET = 'utf8'"] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:25.031539
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Menu_data' doesn't exist [SQL: 'SELECT `Menu_data`.link AS `Menu_data_link`, `Menu_data`.name AS `Menu_data_name` \nFROM `Menu_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:25.039155
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Site_data' doesn't exist [SQL: 'SELECT `Site_data`.site_title AS `Site_data_site_title`, `Site_data`.site_logo AS `Site_data_site_logo`, `Site_data`.fav_icon AS `Site_data_fav_icon` \nFROM `Site_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:30.760570
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Menu_data' doesn't exist [SQL: 'SELECT `Menu_data`.link AS `Menu_data_link`, `Menu_data`.name AS `Menu_data_name` \nFROM `Menu_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:01:30.771222
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'mefisher2$cccs.Site_data' doesn't exist [SQL: 'SELECT `Site_data`.site_title AS `Site_data_site_title`, `Site_data`.site_logo AS `Site_data_site_logo`, `Site_data`.fav_icon AS `Site_data_fav_icon` \nFROM `Site_data`'] (Background on this error at: http://sqlalche.me/e/f405)

TIMESTAMP >>> 2022-01-19 23:06:27.619115
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.631320
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.793510
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:06:27.800008
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:07:58.382623
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:07:59.489308
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:09:24.549688
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:09:25.711014
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:10:41.272212
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:10:42.171145
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:18.161504
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:18.807706
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:12:19.261811
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:13:09.987034
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:13:10.152510
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:22.430885
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:25.491362
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:41.929251
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:15:42.704644
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:21:52.523482
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:22:01.141201
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:20.360597
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:21.461216
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:22.834521
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-19 23:26:49.746459
tuple indices must be integers or slices, not str

TIMESTAMP >>> 2022-01-20 00:53:56.727073
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:01.405486
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:35.839622
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:55.084052
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:54:59.776532
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:55:11.699786
'Announcement' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-20 00:56:25.378439
'Announcement' object is not iterable

TIMESTAMP >>> 2022-01-20 00:56:30.256051
'Announcement' object is not iterable

TIMESTAMP >>> 2022-01-20 01:12:20.800543
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 12, 20, 796172)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:26:08.141849
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 26, 8, 138854)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:26:29.885586
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 26, 29, 882700)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:36:16.112501
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': '', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 36, 16, 110474)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:42:29.606256
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': 'testing event message', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 42, 29, 603264)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-20 01:42:29.607261
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`announcement`.`event_time` at row 1
[SQL: INSERT INTO `Announcement` (message, event_time, create_time) VALUES (%(message)s, %(event_time)s, %(create_time)s)]
[parameters: {'message': 'testing event message', 'event_time': '', 'create_time': datetime.datetime(2022, 1, 20, 1, 42, 29, 603264)}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-20 03:01:20.341090
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:01:29.044253
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:01:37.656507
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:04:08.459261
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:04:56.495786
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:06:52.391441
'str' object is not callable

TIMESTAMP >>> 2022-01-20 03:07:48.099609
'<' not supported between instances of 'NoneType' and 'datetime.datetime'

TIMESTAMP >>> 2022-01-21 00:26:35.238279
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'cccs.announcements' doesn't exist
[SQL: SELECT `Announcements`.event_time AS `Announcements_event_time`, `Announcements`.create_time AS `Announcements_create_time`, `Announcements`.id AS `Announcements_id`, `Announcements`.message AS `Announcements_message` 
FROM `Announcements`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-21 00:26:43.243916
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'cccs.announcements' doesn't exist
[SQL: SELECT `Announcements`.event_time AS `Announcements_event_time`, `Announcements`.create_time AS `Announcements_create_time`, `Announcements`.id AS `Announcements_id`, `Announcements`.message AS `Announcements_message` 
FROM `Announcements`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-21 01:41:46.409871
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:42:28.389158
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:43:05.917478
type object 'datetime.datetime' has no attribute 'datetime'

TIMESTAMP >>> 2022-01-21 01:58:23.725551
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:00:02.126189
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:00:23.899517
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:01.164908
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:03.869136
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:29.284997
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:01:31.185965
Textual column expression 'mefisher2' should be explicitly declared with text('mefisher2'), or use column('mefisher2') for more specificity

TIMESTAMP >>> 2022-01-21 02:04:17.146546
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:04:17.151532
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:05:07.014249
list index out of range

TIMESTAMP >>> 2022-01-21 02:10:26.477882
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:11:37.176924
'BaseQuery' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:12:11.797976
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:15:35.225202
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:18:24.761639
'Registrations' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-21 02:18:58.611545
'Registrations' object has no attribute 'fname'

TIMESTAMP >>> 2022-01-21 02:19:20.771639
'Registrations' object has no attribute 'fname'

TIMESTAMP >>> 2022-01-21 02:31:33.467858
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': '63ad48f6b92910198697eaf362958a75aca2fa4db2663b11d181de0c991a8e2e', 'salt': 'ouC5qExFaePI0cTl', 'code': 'vRhsaDFVjWBMlXiz', 'expiration': datetime.datetime(2022, 1, 21, 2, 46, 33, 462179)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-21 02:32:54.063488
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': 'eb16b895b32dc6bc2368d66392e4a168a73fe87d58c03a4d153f7cfddef60377', 'salt': 'dF3PHKEWlhnL01s6', 'code': 'WeflJg3ktNmqc6yo', 'expiration': datetime.datetime(2022, 1, 21, 2, 47, 54, 55506)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-21 02:36:43.939521
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:36:43.942514
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:41:54.039724
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:41:54.042716
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:43:12.384957
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:43:12.386952
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:43:57.651875
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:43:57.653748
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:44:24.430720
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:44:24.433712
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:45:02.990365
'BaseQuery' object has no attribute 'fiter_by'

TIMESTAMP >>> 2022-01-21 02:45:02.994354
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:46:12.689677
'BaseQuery' object has no attribute 'flter_by'

TIMESTAMP >>> 2022-01-21 02:46:12.691705
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:47:07.117418
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 02:49:36.737063
Python type module cannot be converted

TIMESTAMP >>> 2022-01-21 15:50:45.341009
list index out of range

TIMESTAMP >>> 2022-01-21 15:51:23.159152
list index out of range

TIMESTAMP >>> 2022-01-21 17:40:41.272823
filter() got an unexpected keyword argument 'username'

TIMESTAMP >>> 2022-01-21 17:41:27.808612
filter() got an unexpected keyword argument 'username'

TIMESTAMP >>> 2022-01-21 17:47:48.519493
type object 'Users' has no attribute '_Database_handler__table'

TIMESTAMP >>> 2022-01-21 18:05:26.862738
'str' object has no attribute 'name'

TIMESTAMP >>> 2022-01-21 18:07:31.647279
'str' object has no attribute 'pop'

TIMESTAMP >>> 2022-01-24 01:45:50.075073
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': 'c5871cc364dbbb43066253b29b81c960091424005c675893e39dffeb702c4b20', 'salt': 'oBmgLthpqUEQJCuG', 'code': '4acDnHeQXJyKu1Cp', 'expiration': datetime.datetime(2022, 1, 24, 2, 0, 50, 68093)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-24 01:49:58.119186
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': 'ca26f20ab5477f9f646d53f6bfd103a9389071d9c11a20aa5d7915835e453dea', 'salt': 'PxhJrSVe9goOflM3', 'code': 'EPHvrgbFuAkQW4l6', 'expiration': datetime.datetime(2022, 1, 24, 2, 4, 58, 113202)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-24 01:50:44.510660
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu', 'username': 'mefisher2', 'hashedpassword': '03e1f1fa0174ebbcbf47581773e1d02a068464cce2c55d2c9e6e41c8dee5f92f', 'salt': '7SThlX3QMoEGRvUK', 'code': 'Dia5tYuxIs2gJ89M', 'expiration': datetime.datetime(2022, 1, 24, 2, 5, 44, 504676)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-24 01:52:59.207510
__init__() got an unexpected keyword argument 'registration'

TIMESTAMP >>> 2022-01-24 01:53:07.813696
__init__() got an unexpected keyword argument 'registration'

TIMESTAMP >>> 2022-01-24 01:53:32.115277
__init__() got an unexpected keyword argument 'registration'

TIMESTAMP >>> 2022-01-24 01:55:28.376268
__init__() got an unexpected keyword argument 'registration'

TIMESTAMP >>> 2022-01-24 01:56:05.330813
__init__() got an unexpected keyword argument 'registration'

TIMESTAMP >>> 2022-01-24 02:03:21.695430
list index out of range

TIMESTAMP >>> 2022-01-24 02:03:47.401429
list index out of range

TIMESTAMP >>> 2022-01-24 03:00:14.217499
'Join_team_Request' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-24 03:06:04.713331
'Join_team_Request' object has no attribute '_asdict'

TIMESTAMP >>> 2022-01-24 03:07:37.857314
'event_time'

TIMESTAMP >>> 2022-01-24 03:07:45.666967
'event_time'

TIMESTAMP >>> 2022-01-24 03:45:38.816205
'message' is an invalid keyword argument for Join_team_Request

TIMESTAMP >>> 2022-01-24 03:46:43.984227
'message' is an invalid keyword argument for Join_team_Request

TIMESTAMP >>> 2022-01-24 17:31:49.330372
'Bug_Report' object is not iterable

TIMESTAMP >>> 2022-01-24 17:42:06.063727
'BaseQuery' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-24 17:43:22.239348
'BaseQuery' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 07:50:14.329245
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 07:50:14.330297
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:14.331242
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:14.332250
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:14.333238
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:14.333238
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:20.698986
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 07:50:20.699922
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:20.699922
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:20.700953
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:20.700953
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 07:50:20.701917
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2@cougars.ccis.edu' for key 'email'
[SQL: INSERT INTO `Professor` (title, given_name, family_name, email) VALUES (%(title)s, %(given_name)s, %(family_name)s, %(email)s)]
[parameters: {'title': 'Prof.', 'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mefisher2@cougars.ccis.edu'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:03:08.948814
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Department.code' in 'field list'
[SQL: SELECT `Department`.id AS `Department_id`, `Department`.code AS `Department_code`, `Department`.name AS `Department_name` 
FROM `Department`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-30 09:03:24.127606
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Department.code' in 'field list'
[SQL: SELECT `Department`.id AS `Department_id`, `Department`.code AS `Department_code`, `Department`.name AS `Department_name` 
FROM `Department`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-30 09:09:42.065319
(mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-30 09:09:42.066316
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:42.067288
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:42.067288
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:42.068287
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:42.068287
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:42.070304
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.848334
(mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-30 09:09:47.849331
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.850331
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.850331
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.851326
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.851326
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:09:47.855015
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.554834
(mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-01-30 09:10:35.554834
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.555806
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.555806
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.556803
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.556803
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:10:35.558837
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'name' at row 1
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:12:25.954620
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:12:43.104280
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:12:49.541332
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:14:31.731094
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:14:37.510957
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 09:14:37.511954
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:37.512952
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:37.513949
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:37.514982
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:37.514982
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:37.518936
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.150701
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 09:14:46.151701
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.152695
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.153659
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.154689
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.154689
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:14:46.156649
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'CISS' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'CISS', 'name': 'Computer Science'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:15:11.570840
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:16:20.473106
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 09:16:20.474140
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:16:20.474140
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:16:20.475139
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:16:20.475139
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:16:20.475139
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:16:20.477110
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.934746
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 09:17:33.935791
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.935791
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.936776
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.936776
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.937741
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:17:33.939736
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.899311
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-30 09:18:01.900311
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.900311
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.901308
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.901308
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.902334
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:18:01.904301
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'MATH' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'MATH', 'name': 'Mathematics'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-01-30 09:30:11.570729
'Department' object is not subscriptable

TIMESTAMP >>> 2022-01-30 09:54:08.256473
'dict' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 09:54:53.523624
'dict' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 09:55:46.245166
'dict' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 09:55:54.426039
'dict' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 09:56:07.655129
'dict' object has no attribute 'as_dict'

TIMESTAMP >>> 2022-01-30 12:47:53.685936
Python type dict cannot be converted

TIMESTAMP >>> 2022-01-30 12:48:07.393062
Python type dict cannot be converted

TIMESTAMP >>> 2022-01-30 12:49:30.367469
Python type dict cannot be converted

TIMESTAMP >>> 2022-01-31 11:45:47.337870
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 11:45:49.956350
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 11:46:40.781097
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 11:47:23.982440
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 11:47:50.668490
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 11:48:35.405156
Entity namespace for "Course_Assignments" has no property "user_id"

TIMESTAMP >>> 2022-01-31 12:28:21.379274
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Notes.notes_name' in 'field list'
[SQL: SELECT `Course_Notes`.id AS `Course_Notes_id`, `Course_Notes`.`Course_id` AS `Course_Notes_Course_id`, `Course_Notes`.notes_name AS `Course_Notes_notes_name`, `Course_Notes`.pdf_link AS `Course_Notes_pdf_link` 
FROM `Course_Notes` 
WHERE `Course_Notes`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 6}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-31 12:31:32.181412
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Notes.notes_name' in 'field list'
[SQL: SELECT `Course_Notes`.id AS `Course_Notes_id`, `Course_Notes`.`Course_id` AS `Course_Notes_Course_id`, `Course_Notes`.notes_name AS `Course_Notes_notes_name`, `Course_Notes`.pdf_link AS `Course_Notes_pdf_link` 
FROM `Course_Notes` 
WHERE `Course_Notes`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 6}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-31 12:32:58.503097
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Notes.notes_name' in 'field list'
[SQL: SELECT `Course_Notes`.id AS `Course_Notes_id`, `Course_Notes`.`Course_id` AS `Course_Notes_Course_id`, `Course_Notes`.notes_name AS `Course_Notes_notes_name`, `Course_Notes`.pdf_link AS `Course_Notes_pdf_link` 
FROM `Course_Notes` 
WHERE `Course_Notes`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 6}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-31 12:34:50.318405
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Notes.notes_name' in 'field list'
[SQL: SELECT `Course_Notes`.id AS `Course_Notes_id`, `Course_Notes`.`Course_id` AS `Course_Notes_Course_id`, `Course_Notes`.notes_name AS `Course_Notes_notes_name`, `Course_Notes`.pdf_link AS `Course_Notes_pdf_link` 
FROM `Course_Notes` 
WHERE `Course_Notes`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 6}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-31 12:35:39.854320
'course_id' is an invalid keyword argument for Course_Notes

TIMESTAMP >>> 2022-01-31 12:35:39.868159
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Notes.notes_name' in 'field list'
[SQL: SELECT `Course_Notes`.id AS `Course_Notes_id`, `Course_Notes`.`Course_id` AS `Course_Notes_Course_id`, `Course_Notes`.notes_name AS `Course_Notes_notes_name`, `Course_Notes`.pdf_link AS `Course_Notes_pdf_link` 
FROM `Course_Notes` 
WHERE `Course_Notes`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 6}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-01-31 12:37:31.080102
'course_id' is an invalid keyword argument for Course_Notes

TIMESTAMP >>> 2022-01-31 13:21:55.274695
(mysql.connector.errors.IntegrityError) 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`cccs`.`course_assignments`, CONSTRAINT `course_assignments_ibfk_2` FOREIGN KEY (`Course_id`) REFERENCES `courses` (`id`))
[SQL: DELETE FROM `Courses` WHERE `Courses`.id = %(id_1)s]
[parameters: {'id_1': '6'}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-01-31 13:23:08.172180
(mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'cccs.courses' doesn't exist
[SQL: SELECT `Courses`.id AS `Courses_id`, `Courses`.department_id AS `Courses_department_id`, `Courses`.course_num AS `Courses_course_num`, `Courses`.course_name AS `Courses_course_name`, `Courses`.credit_hour AS `Courses_credit_hour`, `Courses`.link AS `Courses_link` 
FROM `Courses`]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-02-01 11:32:13.495611
'homework_name' is an invalid keyword argument for Course_Homework

TIMESTAMP >>> 2022-02-01 11:32:41.272117
'homework_name' is an invalid keyword argument for Course_Homework

TIMESTAMP >>> 2022-02-01 11:50:10.721918
'pdf_link' is an invalid keyword argument for Course_Homework

TIMESTAMP >>> 2022-02-01 11:50:10.731864
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'Course_Homework.homework_name' in 'field list'
[SQL: SELECT `Course_Homework`.id AS `Course_Homework_id`, `Course_Homework`.`Course_id` AS `Course_Homework_Course_id`, `Course_Homework`.homework_name AS `Course_Homework_homework_name`, `Course_Homework`.due_date AS `Course_Homework_due_date` 
FROM `Course_Homework` 
WHERE `Course_Homework`.`Course_id` = %(Course_id_1)s]
[parameters: {'Course_id_1': 8}]
(Background on this error at: http://sqlalche.me/e/14/f405)

TIMESTAMP >>> 2022-02-01 11:52:26.179395
'pdf_link' is an invalid keyword argument for Course_Homework

TIMESTAMP >>> 2022-02-01 12:38:48.622189
'homework_name' is an invalid keyword argument for Course_Quizzes

TIMESTAMP >>> 2022-02-01 12:49:24.195706
(mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

TIMESTAMP >>> 2022-02-01 12:49:24.196746
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:49:24.197704
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:49:24.197704
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:49:24.198701
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:49:24.198701
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:49:24.199698
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.DataError) 1292 (22007): Incorrect datetime value: '' for column `cccs`.`course_quizzes`.`due_date` at row 1
[SQL: INSERT INTO `Course_Quizzes` (`Course_id`, quiz_name, due_date, pdf_link) VALUES (%(Course_id)s, %(quiz_name)s, %(due_date)s, %(pdf_link)s)]
[parameters: {'Course_id': 8, 'quiz_name': 'Quiz 0101', 'due_date': '', 'pdf_link': 'https://drive.google.com/file/d/1EizopziWpgpKKNEq5ALaMUpi81oh4nXH/preview'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h) (Background on this error at: http://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-02-01 12:55:01.268207
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'mefisher2' for key 'username'
[SQL: INSERT INTO `Registrations` (given_name, family_name, email, username, hashedpassword, salt, code, expiration) VALUES (%(given_name)s, %(family_name)s, %(email)s, %(username)s, %(hashedpassword)s, %(salt)s, %(code)s, %(expiration)s)]
[parameters: {'given_name': 'Michael', 'family_name': 'Fisher', 'email': 'mfisher9542@hotmail.com', 'username': 'mefisher2', 'hashedpassword': '32d582dfd32d87fe404b00fb0d8848dad158dd5d9067bed8f18c0a47057c7187', 'salt': 'iKfNcgtnZAs2loOY', 'code': '9kgOaYPAvpKNrSmt', 'expiration': datetime.datetime(2022, 2, 1, 13, 10, 1, 264247)}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-02-01 12:55:22.063927
list index out of range

TIMESTAMP >>> 2022-02-01 12:56:59.830526
list index out of range

TIMESTAMP >>> 2022-02-01 12:57:44.809770
list index out of range

TIMESTAMP >>> 2022-02-01 13:19:31.471332
'project_name' is an invalid keyword argument for Course_Quizzes

TIMESTAMP >>> 2022-03-02 18:57:54.186267
(mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

TIMESTAMP >>> 2022-03-02 18:57:54.188292
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.189286
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.189286
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.189286
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.190257
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.192253
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

TIMESTAMP >>> 2022-03-02 18:57:54.192253
This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'EX' for key 'code'
[SQL: INSERT INTO `Department` (code, name) VALUES (%(code)s, %(name)s)]
[parameters: {'code': 'EX', 'name': 'example'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)

